name: Deploy (EAS)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: GiGwebs/workflows/.github/workflows/deploy-eas.yml@main
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
